#!/bin/bash
#
sudo /home/pi/uvc-gadget/multi-gadget.sh

#/usr/bin/v4l2-ctl -c auto_exposure=0
#/usr/bin/v4l2-ctl -c auto_exposure_bias=8
#/usr/bin/v4l2-ctl -c contrast=20
#/usr/bin/v4l2-ctl -c video_bitrate=25000000

/usr/bin/v4l2-ctl -c power_line_frequency=2
/usr/bin/v4l2-ctl -c iso_sensitivity_auto=0
/usr/bin/v4l2-ctl -c iso_sensitivity=3
/usr/bin/v4l2-ctl -c auto_exposure=0
/usr/bin/v4l2-ctl -c auto_exposure_bias=24
/usr/bin/v4l2-ctl -c contrast=15
/usr/bin/v4l2-ctl -c sharpness=0
/usr/bin/v4l2-ctl -c video_bitrate=25000000
/usr/bin/v4l2-ctl -c brightness=55
/usr/bin/v4l2-ctl -c scene_mode=0
/usr/bin/v4l2-ctl -c white_balance_auto_preset=2

sudo /home/pi/uvc-gadget/uvc-gadget -u /dev/video1 -v /dev/video0
