#!/bin/bash
#
/usr/bin/v4l2-ctl -c power_line_frequency=2
/usr/bin/v4l2-ctl -c iso_sensitivity_auto=0
/usr/bin/v4l2-ctl -c iso_sensitivity=2
/usr/bin/v4l2-ctl -c auto_exposure=0
/usr/bin/v4l2-ctl -c auto_exposure_bias=20
/usr/bin/v4l2-ctl -c contrast=15
/usr/bin/v4l2-ctl -c sharpness=0
/usr/bin/v4l2-ctl -c video_bitrate=25000000
/usr/bin/v4l2-ctl -c brightness=50
/usr/bin/v4l2-ctl -c scene_mode=0
/usr/bin/v4l2-ctl -c white_balance_auto_preset=3
